### ISSUE TITLE
`TypeError: m.data.map is not a function` when starting the panel with a blank `configuration.json` file

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7-test-panel#118]
If the `/var/lib/docker/volumes/specify7-test-panel_state/_data/configuration.json` file is completely empty and not an empty array (`[]`), you will see the following error:

```
TypeError: m.data.map is not a function

    at m (https://test.specifysystems.org/_next/static/chunks/438-dddd76682e628347.js:1:9067)
    at l (https://test.specifysystems.org/_next/static/chunks/pages/_app-f37bfcff0effa39b.js:1:4021)
    at o (https://test.specifysystems.org/_next/static/chunks/pages/_app-f37bfcff0effa39b.js:1:16245)
    at m (https://test.specifysystems.org/_next/static/chunks/pages/_app-f37bfcff0effa39b.js:1:17256)
    at t.PathnameContextProviderAdapter (https://test.specifysystems.org/_next/static/chunks/main-b73112fada739116.js:1:56853)
    at r (https://test.specifysystems.org/_next/static/chunks/main-b73112fada739116.js:1:15850)
    at et (https://test.specifysystems.org/_next/static/chunks/main-b73112fada739116.js:1:17915)
    at es (https://test.specifysystems.org/_next/static/chunks/main-b73112fada739116.js:1:20892)
```

Make sure to add the two brackets into the file so that this error doesn't happen.

**Comment by grantfitzsimmons** [comment]
Resolved on the production instance, written up here for future reference if someone encounters it.

**Comment by maxpatiiuk** [comment]
If the file doesn't exist, the code will use `[]`:

https://github.com/specify/specify7-test-panel/blob/b166b58df0b0a824681908e9e77142a840c38fd3/app/pages/api/state/index.ts#L29-L30

looks like the bug is that when the file is open, rather than using `[]`, it is using `{}`, which is why JavaScript complains about `.map()` being not a function (`.map()` does not exist on `{}`)
